### ISSUE TITLE
Error replacing search box

### ISSUE THREAD

**Issue by Optimoos** [gbirke/dokuwiki_solr#1]
I'm getting the following error after following your instructions for editing the template:

Fatal error: Call to a member function tpl_searchform() on a non-object in /var/www/html/wiki/lib/tpl/default/main.php on line 66

Not entirely sure what I could be doing wrong to cause this error. Any help?

**Comment by Optimoos** [comment]
This issue ended up being caused by the automated install placing the plugin in a directory named something other than "solr" - along the lines of gbirke_dokuwiki_solr_XXXXXX. Not sure what to do as I suspect that's a github thing, but you might want to look into it.

**Comment by gbirke** [comment]
Thanks for your comment. I have added a line to the README regarding this fact. 

I guess you can't change the generated github folder names and at the moment I'm not very into changing the DokuWiki plugin resolution mechanism.

**Comment by SparklingSoftware** [comment]
If you add a file called plugin.info.txt which contains something like below, it will create the correct plugin folder.

base   git
author Stephan Dekker
email  Stephan@SparklingSoftware.com.au
date   2012-12-02
name   GIT plugin
desc   THis plugin allows you to perform GIT actions. It allows, amongst other things to commit changes locally while asking for a commit message and push to the (master <- default) repository.
url    http://www.dokuwiki.org/plugin:git', http://www.SparklingSoftware.com.au

Cheers,
Stephan

**Comment by gbirke** [comment]
Thanks for the tip, I've added the plugin.info.txt to the refactoring branch of the plugin
